name: rustls-mbedcrypto-provider

permissions:
  contents: read

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-GPL'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE-APACHE'
      - 'LICENSE-GPL'
    branches:
      - master
  merge_group:
  schedule:
    - cron: '0 18 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10

jobs:
  build:
    name: Build+test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust: stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: cargo build (debug; default features)
        run: cargo build --locked

      - name: cargo test (debug; all features)
        run: cargo test --locked --all-features
        env:
          RUST_BACKTRACE: 1
