name: rustls-mbedpki-provider

permissions:
  contents: read

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
    branches:
      - master
  merge_group:
  schedule:
    - cron: '0 18 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: check rustls-mbedpki-provider
      working-directory: rustls-mbedpki-provider
      env:
        RUSTFLAGS: -D warnings
      run: cargo check

    - name: Run rustls-mbedpki-provider tests
      working-directory: rustls-mbedpki-provider
      run: cargo test
