name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: check mbedpki-provider
      working-directory: rustls-mbedpki-provider
      env:
        RUSTFLAGS: -D warnings
      run: cargo check

    - name: Run mbedpki-provider tests
      working-directory: rustls-mbedpki-provider
      run: cargo test
